# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path
name: Main build & publish

on:
  push:
    branches:
      [main, release/**]
  pull_request:
    branches:
      [main, release/**]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'microsoft'
        java-package: jdk
        cache: maven

    - name: Build with Maven
      run: mvn --B --update-snapshots verify

    - name: Publsih to GitHub Packages Apache Maven
      run: mvn deploy -s -B deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
